version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dnd-campaign-manager
    restart: unless-stopped
    ports:
      - "51478:51478"  # NextJS app
      - "56142:56142"  # Storybook
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://dnduser:dndpassword@db:3306/dnd_campaign_manager
      - NEXTAUTH_SECRET=your-secret-key-for-jwt-signing
      - NEXTAUTH_URL=http://localhost:51478
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mariadb:10.11
    container_name: dnd-campaign-manager-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=dnd_campaign_manager
      - MYSQL_USER=dnduser
      - MYSQL_PASSWORD=dndpassword
    volumes:
      - dnd_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app_network

volumes:
  dnd_db_data:
    driver: local

networks:
  app_network:
    external: true